#!/usr/bin/env python

from django.core.management.utils import get_random_secret_key

print("# Here's a SECRET_KEY. Copy it into your settings.env file.")

print('SECRET_KEY='+get_random_secret_key())
