#!/usr/bin/env python
import os
import sys

sys.path.append('/srv/numbas-lti-provider')

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "numbasltiprovider.settings")

from django.core.management import ManagementUtility

def print_info(message):
    print("\n\033[32;1;4m"+str(message)+"\033[0m")

print_info("Setting up the database")
ManagementUtility(['manage.py', 'migrate']).execute()

print_info("Collecting static files")
ManagementUtility(['manage.py', 'collectstatic','--noinput']).execute()

import django
django.setup()
from django.contrib.auth.models import User

SUPERUSER_USER = os.environ['SUPERUSER_USER']
try:
    superuser = User.objects.get(username=SUPERUSER_USER)
except User.DoesNotExist:
    superuser = User.objects.create_superuser(
        SUPERUSER_USER,
        '{}@{}'.format(os.environ['SUPERUSER_USER'], os.environ['SERVERNAME']),
        os.environ['SUPERUSER_PASSWORD']
    )
if not superuser.is_superuser:
    superuser.is_superuser = True
    superuser.save()

print_info("The LTI provider is now ready to run!")
